if ( a>0 ) {
    log("Mayor")
} else {
    log("Menor o igual")
}

if (a>0)
    log("aaa")
else if(a<=0)
    log(-a)
else
    log(test)

if (a>0)
    log("aaa")
else if(a<=0) {
    log(-a)
    hello_world()
} else
    log(test)

for i in [3, 2, 1] {
    print(i)
    print(i + 1)
}

for i in [3, 2, 1]
    print(i)

while(true) {
    a += 1
    b -= 1
}

while(false)
    b /= 1

a == -1
(a || b) && (b || c)

a = {
    b: "hi",
    c: true,
    d: 2.3,
    k: 232,
    f: didi.up
}

b = ["a", 2.3, 4]

log(2 >= 1 + 1)
log(2 == 1 + 1)
log(6 / 2 != 3)
log(4 == 3 + 1 > 2)
log(2 != 1 + 1 > 0)
log(a^2)

log(4 == 3 + 1  && 3 + 1 > 2)
log(2 != 1 + 1 && 1 + 1 > 0)

log(!a)
adsv = "hi"

log("Prueba de suma")
log(suma(1,2))

funcion hola(nombre)
    log("Hola " + nombre + " :D")
end funcion 
hola("nombre")
